# LINKED PROJECTS
# Typology of Terror is not part of this repo, but can be accessed from this domain
[[redirects]]
  from = "/features/typology-of-terror/*"
  to = "https://lowy-digital-terrorism.netlify.com/features/typology-of-terror/:splat"
  status = 200

# PAM Project Evaluations is not part of this repo, but can be accessed from this domain
[[redirects]]
  from = "/pacific-aid-map/*"
  to = "https://lowy-pam.netlify.app/pacific-aid-map/:splat"
  status = 200

# Chinese Communities Poll is not part of this repo, but can be accessed from this domain
[[redirects]]
  from = "/features/chinese-communities/*"
  to = "https://lowy-institute-chinese-communities.netlify.app/features/chinese-communities/:splat"
  status = 200

# Diplomatic postings is not part of this repo, but can be accessed from this domain
[[redirects]]
  from = "/features/diplomat-database/*"
  to = "https://lowy-institute-diplomat-database.netlify.app/features/diplomat-database/:splat"
  status = 200

# ARCHIVED CONTENT
# interactives.lowyinstitute.org
[[redirects]]
  from = "/fonops_maps/Overview.html"
  to = "/archive/fonops"
  status = 301
[[redirects]]
  from = "/fonops_maps/*"
  to = "/archive/fonops/:splat"
  status = 301
[[redirects]]
  from = "/publications/the-prime-ministers-in-washington"
  to = "/archive/the-prime-ministers-in-america"
  status = 301
[[redirects]]
  from = "/publications/the-prime-ministers-in-washington-notes"
  to = "/archive/the-prime-ministers-in-america/notes"
  status = 301
[[redirects]]
  from = "/publications/the-prime-ministers-in-america"
  to = "/archive/the-prime-ministers-in-america"
  status = 301
[[redirects]]
  from = "/publications/pacific-aid-map-country-profiles"
  to = "/archive/pacific-aid-map-country-profiles"
  status = 301
[[redirects]]
  from = "/publications/PNGin2017/png-in-2017-home.html"
  to = "/archive/png-in-2017"
  status = 301
[[redirects]]
  from = "/publications/PNGin2017/*"
  to = "/archive/png-in-2017/:splat"
  status = 301

# publications.lowyinstitute.org
[[redirects]]
  from = "/shanahan/charities-and-terrorism-lessons-from-the-syrian-crisis.html"
  to = "/archive/charities-and-terrorism-lessons-from-the-syrian-crisis"
  status = 301

# Moved content
[[redirects]]
  from = "/features/indonesia-votes/"
  to = "/features/indonesia-votes-2019/"
  status = 301

[[redirects]]
  from = "/features/australian-attitudes-to-climate-change/"
  to = "https://www.lowyinstitute.org/issues/australia-climate-change"
  status = 301

# OTHER CONFIG
[[headers]]
  # Allow CORS on fonts for emails, etc.
  for = "/fonts/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
