title: >
  Total battle force ships, US Navy and Chinese&nbsp;PLA&nbsp;Navy

source: >
  <b>Source:</b> Lorem ipsum

notes: >
  <b>Notes:</b> Lorem ipsum

subtitle: >
  Values beyond 2020 are estimates

axes:
  minY: 200
  maxY: 450
  stepsY: 6
  rotateX: true
  percentage: false
  minorLines: true
  dotted: [] # Index of dotted gridlines
  reverse: false
  guideLine: null # value of optional horizontal line. set 'null' if disabled

series:
  -
    title: Year
    values:
      - 2005
      - 2006
      - 2007
      - 2008
      - 2009
      - 2010
      - 2011
      - 2012
      - 2013
      - 2014
      - 2015
      - 2016
      - 2017
      - 2018
      - 2019
      - 2020
      - 2021
      - 2022
      - 2023
      - 2024
      - 2025
      - 2026
      - 2027
      - 2028
      - 2029
      - 2030

  -
    title: US LOB
    color: "blue-100"
    widen: false
    dashed: true
    values:
      - 270
      - 320
      
  -
    title: PLA LOB
    color: "red"
    widen: false
    dashed: true
    values:
      - 210
      - 431

  -
    title: PLA Navy
    color: "red"
    widen: true
    dashed: false
    values:
      - 216
      - 221
      - 222
      - 233
      - 262
      - 276
      - 276
      - 271
      - 273
      - 283
      - 294
      - 303
      - 317
      - 306
      - 335
      - 333
      - 346
      - 359
      - 372
      - 385
      - 400
      - 405
      - 410
      - 415
      - 420
      - 425

  -
    title: US Navy
    color: "blue-100"
    widen: true
    dashed: false
    values:
      - 291
      - 282
      - 281
      - 279
      - 282
      - 285
      - 288
      - 284
      - 287
      - 285
      - 289
      - 271
      - 275
      - 279
      - 286
      - 296
      - 305
      - 311
      - 314
      - 314
      - 313
      - 314
      - 316
      - 322
      - 325
      - 331
